root:
  - /
  - /en

om_oss:
  - /om-oss
  - /en/about-us

confirmation:
  - /takk
  - /en/thanks

design_utvikling:
  - /design-utvikling
  - /en/design-development

seo_marketing:
  - /seo-markedsforing
  - /en/seo-marketing

hosting_drift:
  - /hosting-drift
  - /en/hosting-support